
title: Синдром Утёнка
author:
  name: Author Name
  email: syndrome@gmail.com
description: >-
  Лендинг подкаста Синдром Утёнка
baseurl: ""
url: "https://ducksyndrome.github.io"

plugins:
  - jekyll-feed

minima:
  skin: classic

  social_links:
      twitter: alprog_
      telegram: alprog
      instagram: alprog_
      github: alprog
      linkedin: alprog

