
title: Синдром Утёнка
description: Подкаст «Синдром Утёнка»
baseurl: ""
url: "https://ducksyndrome.github.io"

disqus:
  shortname: ducksyndrome

plugins:
  - jekyll-feed

minima:
  skin: classic

  social_links:
      twitter: web_lain
      telegram: web_lain

